api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"