security:

    encoders:
        ApiBundle\Entity\Usuario: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false
        
        api_oauth:
            pattern:    ^/api/autenticacion
            stateless:  true
            anonymous:  true 

        api_rutas:
            pattern:    ^/api/doc
            stateless:  true
            anonymous:  true 

        api_registrar:
            pattern:    ^/api/usuario/registrar
            stateless:  true
            anonymous:  true 

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false

        main:
            anonymous: ~
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    role_hierarchy:
       # ROLE_ADMIN:       ROLE_USER
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registrar, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/historial, role: ROLE_ADMIN }