api_usuario:
    type: rest
    prefix: usuario
    resource: ApiBundle\Controller\UsuarioController

api_lote:
    type: rest
    prefix: lote
    resource: ApiBundle\Controller\LoteController

api_siembra:
    type: rest
    prefix: siembra
    resource: ApiBundle\Controller\SiembraController

api_cosecha:
    type: rest
    prefix: cosecha
    resource: ApiBundle\Controller\CosechaController

api_cultivo:
    type: rest
    prefix: cultivo
    resource: ApiBundle\Controller\CultivoController

api_provincia:
    type: rest
    prefix: provincia
    resource: ApiBundle\Controller\ProvinciaController

api_reportes:
    type: rest
    prefix: reportes
    resource: ApiBundle\Controller\ReportesController